# Generated by Django 4.2.7 on 2026-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('degree', models.CharField(choices=[('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=10, verbose_name='المرحلة الدراسية')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.CharField(choices=[('19:00', '19:00 - 7 مساءً'), ('20:00', '20:00 - 8 مساءً'), ('21:00', '21:00 - 9 مساءً'), ('22:00', '22:00 - 10 مساءً'), ('23:00', '23:00 - 11 مساءً'), ('00:00', '00:00 - 12 منتصف الليل')], max_length=5, verbose_name='ساعة الحضور')),
                ('reason', models.TextField(verbose_name='دليل المراجعة')),
                ('duration', models.CharField(max_length=50, verbose_name='مدة الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_date', models.DateField(verbose_name='تاريخ الأرشيف')),
                ('appointments_data', models.JSONField(verbose_name='بيانات المواعيد')),
                ('total_count', models.IntegerField(default=0, verbose_name='العدد الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'أرشيف يومي',
                'verbose_name_plural': 'الأرشيف اليومي',
                'ordering': ['-archive_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('total_appointments', models.IntegerField(default=0, verbose_name='إجمالي المواعيد')),
                ('master_count', models.IntegerField(default=0, verbose_name='عدد طلاب الماجستير')),
                ('phd_count', models.IntegerField(default=0, verbose_name='عدد طلاب الدكتوراه')),
                ('time_slot_data', models.JSONField(default=dict, verbose_name='بيانات الأوقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقرير شهري',
                'verbose_name_plural': 'التقارير الشهرية',
                'ordering': ['-month'],
            },
        ),
    ]
