# Generated by Django 4.2.7 on 2026-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time'], 'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='dailyarchive',
            options={'ordering': ['-archive_date'], 'verbose_name': 'بایگانی روزانه', 'verbose_name_plural': 'بایگانی\u200cهای روزانه'},
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-month'], 'verbose_name': 'گزارش ماهانه', 'verbose_name_plural': 'گزارش\u200cهای ماهانه'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(verbose_name='تاریخ نوبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(max_length=10, verbose_name='ساعت حضور'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='degree',
            field=models.CharField(choices=[('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=10, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='مدت حضور'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(verbose_name='دلیل مراجعه'),
        ),
        migrations.AlterField(
            model_name='dailyarchive',
            name='appointments_data',
            field=models.JSONField(verbose_name='داده\u200cهای نوبت\u200cها'),
        ),
        migrations.AlterField(
            model_name='dailyarchive',
            name='archive_date',
            field=models.DateField(verbose_name='تاریخ بایگانی'),
        ),
        migrations.AlterField(
            model_name='dailyarchive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dailyarchive',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='تعداد کل'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='master_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دانشجویان ارشد'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.DateField(verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='phd_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دانشجویان دکترا'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='time_slot_data',
            field=models.JSONField(default=dict, verbose_name='داده\u200cهای زمانی'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='total_appointments',
            field=models.IntegerField(default=0, verbose_name='مجموع نوبت\u200cها'),
        ),
    ]
