# Generated by Django 4.2.7 on 2026-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_dailyarchive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('passport_name', models.CharField(max_length=200, verbose_name='الاسم بحسب الجواز')),
                ('degree', models.CharField(choices=[('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=10, verbose_name='المقطع')),
                ('major', models.CharField(max_length=200, verbose_name='التخصص')),
                ('university_type', models.CharField(choices=[('نفقة خاصة', 'نفقة خاصة'), ('ابتعاث', 'ابتعاث')], max_length=50, verbose_name='نوع الجامعة')),
                ('bachelor_university', models.CharField(max_length=200, verbose_name='جامعة البكالوريوس')),
                ('master_university', models.CharField(blank=True, max_length=200, null=True, verbose_name='جامعة الماجستير')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('passport_url', models.URLField(blank=True, null=True, verbose_name='رابط جواز السفر')),
                ('bachelor_cert_url', models.URLField(blank=True, null=True, verbose_name='رابط شهادة البكالوريوس')),
                ('master_cert_url', models.URLField(blank=True, null=True, verbose_name='رابط شهادة الماجستير')),
                ('bachelor_transcript_url', models.URLField(blank=True, null=True, verbose_name='رابط كشف درجات البكالوريوس')),
                ('master_transcript_url', models.URLField(blank=True, null=True, verbose_name='رابط كشف درجات الماجستير')),
                ('filled_form_url', models.URLField(blank=True, null=True, verbose_name='رابط الاستمارة المعبأة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('google_sheet_row', models.IntegerField(blank=True, null=True, verbose_name='رقم الصف في الشيت')),
            ],
            options={
                'verbose_name': 'تسجيل طالب',
                'verbose_name_plural': 'تسجيلات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DailyArchive',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
