# Generated by Django 4.2.7 on 2026-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_studentregistration_delete_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='bachelor_cert_url',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='bachelor_transcript_url',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='bachelor_university',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='filled_form_url',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='master_cert_url',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='master_transcript_url',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='master_university',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='address_iraq',
            field=models.CharField(default='', max_length=300, verbose_name='العنوان في العراق'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='bachelor_gpa',
            field=models.CharField(default='', max_length=50, verbose_name='معدل البكالوريوس'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='children_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأطفال'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='job',
            field=models.CharField(default='', max_length=200, verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='marital_status',
            field=models.CharField(choices=[('مجرد', 'مجرد'), ('متأهل', 'متأهل')], default='مجرد', max_length=20, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='master_gpa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='معدل الماجستير'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='transcript_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط كشف درجات'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='university_form_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط استمارة التحصيل الجامعي'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='passport_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط عکس پاسپورت'),
        ),
    ]
