# Generated by Django 4.2.7 on 2026-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_studentregistration_bachelor_cert_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='master_transcript_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط كشف درجات الماجستير'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='transcript_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط كشف درجات البكالوريوس'),
        ),
    ]
