# Generated by Django 4.2.7 on 2026-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_studentregistration_master_transcript_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='passport_name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='لقب العائلة'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='middle_name',
            field=models.CharField(default='', max_length=200, verbose_name='الاسم الثلاثي'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='previous_university',
            field=models.CharField(default='', max_length=300, verbose_name='الجامعة السابقة'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='religion',
            field=models.CharField(default='', max_length=50, verbose_name='الديانة'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='marital_status',
            field=models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], default='أعزب', max_length=20, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='رقم الهاتف'),
        ),
    ]
